
### Saludo
GET http://localhost:8080/saludo

### Saludo con un nombre dado por parámetro
GET http://localhost:8080/saludo/Carlos

### Saludo con un nombre dado por parámetro usando dos parametros
GET http://localhost:8080/saludo/Juan/25

### Saludo con un nombre dado por parámetro usando dos parametros
POST http://localhost:8080/saludo

### Saludo con un nombre dado por parámetro
GET http://localhost:8080/saludo/Carlos

